PROJECT_VERSION = "0.6.2"
API_VERSION = PROJECT_VERSION
MARKET_DATA_MODEL_VERSION = f"market-data-v{PROJECT_VERSION}"
RISK_MODEL_VERSION = f"cre-v{PROJECT_VERSION}"
LIFECYCLE_MODEL_VERSION = f"cre-v{PROJECT_VERSION}"
PORTFOLIO_ACTION_MODEL_VERSION = f"cre-v{PROJECT_VERSION}"
MONITORING_MODEL_VERSION = f"monitoring-v{PROJECT_VERSION}"
