PROJECT_VERSION = "0.3.1"
API_VERSION = PROJECT_VERSION
MARKET_DATA_MODEL_VERSION = "market-data-v0.3.1"
RISK_MODEL_VERSION = "cre-v0.3.1"
LIFECYCLE_MODEL_VERSION = "cre-v0.3.1"
PORTFOLIO_ACTION_MODEL_VERSION = "cre-v0.3.1"
